# Generated by Django 4.0 on 2022-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_id_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=models.CharField(default=models.CharField(max_length=200), max_length=100, primary_key=True, serialize=False), max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='userName',
            field=models.CharField(default=models.CharField(max_length=200), max_length=100, primary_key=True, serialize=False),
        ),
    ]
